# Site
title: Portfolio
description: "stuff happens here"
url: https://clearlyjustmayo.tk
logo: "logo.png"                                     # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.jpg                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-6.jpg             # this image will be shown on post list page
  default-post: images/unsplash-image-4.jpg   # this image will be shown when post's front matter doesn't specify any image
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/posts/:year/:title"
      comments: true
# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:              mayo9s@pm.me
#google.plus:        username
#twitter:            username
facebook:           azurpha
github:             clearlyjustmayo
linkedin:           leonchiew
#xing:              username
instagram:          clearlyjustmayo
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
flickr:             clearlyjustmayo
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
